# Site-wide settings
# ------------------
#
title: RECOMB 2027
iteration: "31st"
location: "Toronto, Canada"
city: "Toronto"
country: "Canada"

#
author:
   name: RECOMB Conference
   email: info@recombconf.org
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.


# Build settings
# --------------
#
# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima
#
# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
# remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
social_links:
    - title: Email 
      icon: envelope
      url: "mailto:info@recombconf.org"
    - title: RECOMB at X 
      icon: x-twitter
      url: "https://x.com/RECOMBconf"
    - title: RECOMB at BlueSky 
      icon: bluesky
      url: "https://bsky.app/profile/recombconf.bsky.social"
    - title: RECOMB at LinkedIn
      icon: linkedin
      url : "https://www.linkedin.com/company/recombconf"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.

hide_site_feed_link: true

main_navigation:
  - title: About
    url: https://recomb.org/
    external: true
  - title: Conference
    children:
      - title: Committees
        url: /committees
      - title: Key dates & Deadlines
        url: /keydates_and_deadlines
      - title: Call for Papers
        url: /call_for_papers
      - title: Call for Abstracts
        url: /call_for_abstracts
  - title: Register
    children:
      - title: RECOMB and Satellites
        url: /how_to_register
      - title: Travel Fellowships
        url: /travel_fellowships
  - title: Program
    children:
      - title: Program Schedule
        url: /program
      - title: Keynotes
        url: /keynotes
      - title: Poster Guidelines
        url: /posters
  - title: Venue
    children:
      - title: Main Conference Venue
        url: /venue_main
      - title: Satellites Venue
        url: /venue_satellites
      - title: Hotels
        url: /hotels
      - title: Airport Directions
        url: /airport
      - title: Things to do in Toronto
        url: /things_to_do
      - title: Local Transportation
        url: /transportation
      - title: Visa Information
        url: /visa
  - title: Satellites
    children:
      - title: RECOMB-Seq
        url: https://recomb-seq.github.io/
        external: true
      - title: RECOMB-CCB
        url: https://recomb.org/recomb-ccb2027
        external: true
      - title: RECOMB-CG
        url: https://recomb-cg.org/
        external: true
      - title: RECOMB-Genetics
        url: /recombgenetics
      - title: RECOMB-Privacy
        url: https://recomb-privacy.github.io/
        external: true
#      - title: RECOMB-Arch
#        url: https://recomb-arch.github.io/
#        external: true
#      - title: RECOMB-RSG
#        url: https://recomb-rsg.github.io/
#        external: true
  - title: Sponsors
    children:
      - title: RECOMB Sponsors
        url: /sponsors
      - title: Sponsorship Packages
        url: /sponsorship_packages

#  Moved this to the Conference tab
#  - title: About RECOMB
#    url: https://www.recomb.org
#    external: true

# Custom variables	
deadlines:
  abstract_submission: "October 28th, 2026, 23:59 AoE"
  paper_submission: "November 4th, 2026, 23:59 AoE"
  author_notification: "December 20th, 2026"
  final_version: "TBA"
  early_registration: "TBA"
  late_registration: "TBA"
  highlights_submission: "TBA"
  highlights_notification: "TBA"
  highlights_cutoff: "TBA" # earliest journal pub date for highlights submissions
  poster_submission: "TBA"
  poster_notification: "TBA"
#  late_poster_submission: "15 April 2027, 23:59 AoE"
#  late_poster_notification: "20 April 2027"
  travel_fellow_application: "TBA"
  travel_fellow_notification: "TBA"
  conference_dates: "May 17-20, 2027"
  satellite_dates: "May 15-16, 2027" # for the home page
  satellite_seq: "May 15-16, 2027"
  satellite_ccb: "May 15-16, 2027"
  satellite_cg: "May 15-16, 2027"
  satellite_genetics: "May 16th, 2027"
  satellite_priv: "May 15th, 2027"
  satellite_arch: "24 May 2027"
  satellite_rsg: "25 May 2027"
  
links: 
  easychair: "https://easychair.org/conferences/?conf=recomb2027"
 
team:
  oc_chair1: "Michael Brudno"
  oc_chair1_email: "brudno@cs.toronto.edu"
  oc_chair1_institute: "Toronto University"
  oc_chair1_url: "https://brudno.uhndata.io/"
  oc_chair2: ""
  oc_chair2_email: ""
  oc_chair2_institute: ""
  oc_member1: ""
  oc_member1_url: ""
  oc_member1_institute: "Toronto University"
  oc_member2: ""
  oc_member2_institute: "Toronto University"
  pc_chair: "Rohit Singh"
  pc_chair_email: "rohit.singh@duke.edu"
  pc_chair_institute: "Duke University"
  pc_chair_url: "https://singhlab.net/"
  publicity_chair: ""
  publicity_chair_email: ""
  publicity_chair_institute: ""
  publicity_chair_url: ""
  highlights_chair: ""
  highlights_chair_email: ""
  highlights_chair_institute: ""
  highlights_chair_url: ""
  posters_chair: ""
  posters_chair_email: ""
  posters_chair_institute: ""
  posters_chair_url: ""
  travel_fellowship_chair: ""
  travel_fellowship_chair_email: ""
  travel_fellowship_chair_institute: ""
  travel_fellowship_chair_url: ""
  industry_chair: ""
  industry_chair_email: ""
  industry_chair_institute: ""
  industry_chair_url: ""

#  nav_pages:
#     - about.md
#     - committes.md
#     - register.md
#
#   Set to `true` to show excerpts on the homepage.
#   show_excerpts: false 
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"
#

